add new customer api
mchekini-check-consulting/staff-manager-api pull request #4
Opened 2023-07-13 10:12 UTC by dihia-lyz

**add new customer api with:**
  -  fileads validation 
  - check if email already exist
**add unit and integration tests**

2023-07-13 11:35 UTC, mchekini-check-consulting requested changes

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/main/java/com/example/staffmanagerapi/resource/CustomerController.java
> +@CrossOrigin(origins = "*")
Avec notre configuration actuelle, on aura plus besoin d'utiliser cette annotation

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/main/java/com/example/staffmanagerapi/resource/CustomerController.java
> +    @Autowired
De préférence, utiliser les injections par constructeur au lieu d'utiliser les injections par champs

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/main/java/com/example/staffmanagerapi/resource/CustomerController.java
> +            if (customerRepository.existsByCustomerEmail(customer.getCustomerEmail())) {
La plupart de la logique décrite dans ce Controller doit être dans le service
Faire un peu de refacto
Essaie d'éviter de passer des paramètres null au maximum

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/main/resources/application-local.yml
> +    password: 1234
A ne pas pusher, car ça concerne que ta configuration locale :p

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/main/resources/application.yml
> +    active: local
même remarque, lié à ta configuration à toi

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/test/java/com/example/staffmanagerapi/intergration/CustomerTest.java
> +        //Errors
Le nom du test n'est pas cohérent avec le contenu

2023-07-13 11:35 UTC, mchekini-check-consulting commented on src/test/java/com/example/staffmanagerapi/intergration/CustomerTest.java
> +        assertEquals(400, responseHandler.get("statusCode"));
Le test n'est pas censé passer dans ce cas ? je m'attendais à un 201

Et plus globalement, faudra tester tous les cas, les cas passants et les non passants

2023-07-13 13:19 UTC, dihia-lyz commented
Bien reçu, je vai revoir sa rapidement

Le jeu. 13 juil. 2023 à 12:35, mchekini-check-consulting <
***@***.***> a écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pom.xml
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262381395>
> :
>
> > @@ -83,6 +83,24 @@
>              <artifactId>spring-boot-starter-test</artifactId>
>              <scope>test</scope>
>          </dependency>
> +        <dependency>
> +            <groupId>org.springframework.boot</groupId>
> +            <artifactId>spring-boot-starter-validation</artifactId>
> +            <version>3.0.4</version>
> +        </dependency>
> +        <dependency>
> +            <groupId>org.modelmapper</groupId>
> +            <artifactId>modelmapper</artifactId>
> +            <version>3.1.1</version>
> +        </dependency>
> +        <!-- https://mvnrepository.com/artifact/com.guicedee.services/sl4j -->
> +        <dependency>
> +            <groupId>com.guicedee.services</groupId>
> +            <artifactId>sl4j</artifactId>
>
> Je pense que y'a déjà une lib pour gérer les logs sur le projet
>
> Faudra juste ajouter l'annotation @slf4j <https://github.com/slf4j> sur
> la classe
> ------------------------------
>
> In
> src/main/java/com/example/staffmanagerapi/configuration/SecurityConfiguration.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262385498>
> :
>
> > @@ -7,13 +7,13 @@
>  import org.springframework.security.web.SecurityFilterChain;
>
>  @Configuration
> ***@***.***
> ***@***.***
>
> Tu peux supprimer le commentaire
> ------------------------------
>
> In src/main/java/com/example/staffmanagerapi/dto/CustomerCreationDto.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262386614>
> :
>
> > +import jakarta.validation.constraints.Pattern;
> +import jakarta.validation.constraints.Size;
> +import lombok.AllArgsConstructor;
> +import lombok.Builder;
> +import lombok.Data;
> +import lombok.NoArgsConstructor;
> +import org.springframework.stereotype.Component;
> +
> ***@***.***
> ***@***.***
> ***@***.***
> ***@***.***
> ***@***.***
> +public class CustomerCreationDto {
> +
> +    @Pattern(regexp = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w\\w+)(\\s)*$",
>
> Autant utiliser @Email qui est beaucoup plus lisible
> ------------------------------
>
> In src/main/java/com/example/staffmanagerapi/model/Customer.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262393893>
> :
>
> > +import lombok.NoArgsConstructor;
> +import org.springframework.context.annotation.Scope;
> +import org.springframework.context.annotation.ScopedProxyMode;
> +import org.springframework.stereotype.Component;
> +import org.springframework.web.context.WebApplicationContext;
> +
> ***@***.***
> ***@***.***
> ***@***.***
> ***@***.***
> ***@***.***
> ***@***.***
> +public class Customer {
> +    @Id
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "customer_seq")
> +    @SequenceGenerator(name="customer_seq", sequenceName = "customer_seq", allocationSize = 1)
>
> A t'on besoin d'utiliser une séquence pour un comportement par défaut (
> incrémentation de 1)
> ------------------------------
>
> In
> src/main/java/com/example/staffmanagerapi/resource/CustomerController.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262395295>
> :
>
> > +import lombok.extern.slf4j.Slf4j;
> +import org.modelmapper.ModelMapper;
> +import org.springframework.beans.factory.annotation.Autowired;
> +import org.springframework.http.HttpStatus;
> +import org.springframework.http.ResponseEntity;
> +import org.springframework.stereotype.Component;
> +import org.springframework.validation.BindingResult;
> +import org.springframework.web.bind.annotation.*;
> +
> +import java.util.List;
> +import java.util.stream.Collectors;
> +
> +
> ***@***.***("api")
> ***@***.***
> ***@***.***(origins = "*")
>
> Avec notre configuration actuelle, on aura plus besoin d'utiliser cette
> annotation
> ------------------------------
>
> In
> src/main/java/com/example/staffmanagerapi/resource/CustomerController.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262396184>
> :
>
> > +import org.springframework.stereotype.Component;
> +import org.springframework.validation.BindingResult;
> +import org.springframework.web.bind.annotation.*;
> +
> +import java.util.List;
> +import java.util.stream.Collectors;
> +
> +
> ***@***.***("api")
> ***@***.***
> ***@***.***(origins = "*")
> ***@***.***
> ***@***.***
> +public class CustomerController {
> +
> +    @Autowired
>
> De préférence, utiliser les injections par constructeur au lieu d'utiliser
> les injections par champs
> ------------------------------
>
> In
> src/main/java/com/example/staffmanagerapi/resource/CustomerController.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262398803>
> :
>
> > ***@***.***(origins = "*")
> ***@***.***
> ***@***.***
> +public class CustomerController {
> +
> +    @Autowired
> +    private CustomerService customerService;
> +    @Autowired
> +    private CustomerRepository customerRepository;
> +    @Autowired
> +    private ModelMapper modelMapper;
> +
> +    @PostMapping("customer")
> +    public ResponseEntity<?> ***@***.*** @Valid CustomerCreationDto customer, BindingResult bindingResult) {
> +        try {
> +            if (customerRepository.existsByCustomerEmail(customer.getCustomerEmail())) {
>
> La plupart de la logique décrite dans ce Controller doit être dans le
> service
> Faire un peu de refacto
> Essaie d'éviter de passer des paramètres null au maximum
> ------------------------------
>
> In src/main/resources/application-local.yml
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262401262>
> :
>
> > @@ -2,7 +2,7 @@ spring:
>    datasource:
>      url: jdbc:postgresql://localhost:5433/postgres
>      username: postgres
> -    password: postgres
> +    password: 1234
>
> A ne pas pusher, car ça concerne que ta configuration locale :p
> ------------------------------
>
> In src/main/resources/application.yml
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262401721>
> :
>
> > \ No newline at end of file
> +    active: local
>
> même remarque, lié à ta configuration à toi
> ------------------------------
>
> In
> src/test/java/com/example/staffmanagerapi/intergration/CustomerTest.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262404020>
> :
>
> > +                .build();
> +
> +        HttpHeaders headers = new HttpHeaders();
> +        headers.setContentType(MediaType.APPLICATION_JSON);
> +        HttpEntity<Customer> requestEntity = new HttpEntity<>(customer, headers);
> +
> +        ResponseEntity<Object> response = restTemplate.postForEntity(
> +                "http://localhost:" + port + "/api/customer",
> +                requestEntity,
> +                Object.class
> +        );
> +
> +        Map<?, ?> responseHandler = convertResponseEntityToMap(response.getBody());
> +        Map<String, String> resultMap = convertFieldsErrorsToHashMap(responseHandler.get("data"));
> +
> +        //Errors
>
> Le nom du test n'est pas cohérent avec le contenu
> ------------------------------
>
> In
> src/test/java/com/example/staffmanagerapi/intergration/CustomerTest.java
> <https://github.com/mchekini-check-consulting/staff-manager-api/pull/4#discussion_r1262405799>
> :
>
> > +
> +        HttpHeaders headers = new HttpHeaders();
> +        headers.setContentType(MediaType.APPLICATION_JSON);
> +        HttpEntity<Customer> requestEntity = new HttpEntity<>(customer, headers);
> +
> +        ResponseEntity<Object> response = restTemplate.postForEntity(
> +                "http://localhost:" + port + " [...]

2023-07-13 14:16 UTC, HL-Abdallah requested changes

2023-07-13 14:16 UTC, HL-Abdallah commented on src/main/java/com/example/staffmanagerapi/dto/CustomerCreationDto.java
> +    @Pattern(regexp = "^fr\\d{11}$", message="Numero TVA non valide")
```suggestion
    @NotNull
    @Pattern(regexp = "^fr\\d{11}$", message="Numero TVA non valide")
```

2023-07-13 14:16 UTC, HL-Abdallah commented on src/main/java/com/example/staffmanagerapi/dto/CustomerCreationDto.java
> +    @Pattern(regexp = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w\\w+)(\\s)*$",
```suggestion
    @NotNull
    @Pattern(regexp = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w\\w+)(\\s)*$",
```

2023-07-14 12:02 UTC, mchekini-check-consulting approved these changes

2023-07-14 12:19 UTC, sidisaidkarim commented on src/main/java/com/example/staffmanagerapi/dto/CustomerCreationDto.java
> +    @NotNull(message = "Numéro TVA non valide")
pour le @NotNull annotation le message devrait etre "le numéro de tva est obligatoire"

2023-07-14 12:39 UTC, sidisaidkarim approved these changes

2023-07-14 14:01 UTC, merged